import type {
  ResolvedGlobalConfig,
  PageSection,
  ResolvedProductsPageConfig,
  ResolvedLocationsPageConfig,
} from '@/lib/types/cms';

// ─── Default Configuration ─────────────────────────────────────────────────────────────
// Default configuration for the site.

export const defaultGlobalConfig: ResolvedGlobalConfig = {
  siteName: 'GOOFY SHOP',
  siteDescription: 'GOOFY is the first skateboard shop and skate community in Laos. Built for the streets, worn by the culture.',
  logoUrl: null,
  faviconUrl: null,
  mainMenu: [
    { label: 'Shop', url: '/', iconName: null, openInNewTab: false },
    { label: 'Drops', url: '/drop', iconName: 'star', openInNewTab: false },
    { label: 'Products', url: '/products', iconName: null, openInNewTab: false },
    { label: 'About', url: '/about', iconName: null, openInNewTab: false },
  ],
  navigation: {
    shopMenu: {
      godMode: true,
      enabled: true,
      categoryLimit: 4,
      trendingLimit: 4,
    },
  },
  announcement: {
    active: true,
    items: [
      '* Free Shipping Over $150',
      '* New Drop Coming Soon',
      '* Limited Stock Available',
      '* 1 Per Customer',
    ],
    barColor: '#e52521',
  },
  theme: {
    primary: '#e52521',
    secondary: '#049cd8',
    background: '#f7f7f5',
    foreground: '#111111',
  },
  saleEndDate: null,
  footer: {
    copyrightText: '(c) 2026 Goofy Shop. All rights reserved.',
    socialLinks: [
      { platform: 'instagram', url: '#' },
      { platform: 'twitter', url: '#' },
      { platform: 'youtube', url: '#' },
      { platform: 'facebook', url: '#' },
    ],
  },
  ui: {
    addToCartText: 'Add to Cart',
    soldOutText: 'Sold Out',
  },
  godMode: {
    enabled: true,
    aboveFold: {
      showNavbar: true,
      showMarqueeTicker: true,
      showHeroBanner: true,
    },
    content: {
      showFeaturedDrops: true,
      showCountdownTimer: true,
      showCollabSpotlight: false,
      showLookbookBanner: false,
      showShopByCategory: true,
      collabTitle: 'Collab Spotlight',
      collabDescription: 'Featuring our latest collab drop.',
      collabCtaText: 'Explore Collab',
      collabCtaLink: '/products',
      collabImageUrl: null,
      lookbookTitle: 'Lookbook',
      lookbookSubtitle: 'Lifestyle visuals from the latest collection.',
      lookbookCtaText: 'View Lookbook',
      lookbookCtaLink: '/products',
      lookbookImageUrl: null,
    },
    socialProof: {
      showTestimonials: false,
      testimonials: [
        { quote: 'Best deck setup I have ridden this year.', author: 'Mason R.' },
        { quote: 'Fast shipping and premium quality every time.', author: 'Aiko T.' },
      ],
      showPressLogos: true,
      pressLogos: [
        { name: 'BAKER', url: 'https://www.bakerskateboards.com', logoUrl: 'https://logo.clearbit.com/bakerskateboards.com' },
        { name: 'PALACE', url: 'https://www.palaceskateboards.com', logoUrl: 'https://logo.clearbit.com/palaceskateboards.com' },
        { name: 'PRIMITIVE', url: 'https://primitiveskate.com', logoUrl: 'https://logo.clearbit.com/primitiveskate.com' },
        { name: 'ENJOI', url: 'https://enjoico.com', logoUrl: 'https://logo.clearbit.com/enjoico.com' },
        { name: 'SANTA CRUZ', url: 'https://santacruzskateboards.com', logoUrl: 'https://logo.clearbit.com/santacruzskateboards.com' },
        { name: 'ELEMENT', url: 'https://www.elementbrand.com', logoUrl: 'https://logo.clearbit.com/elementbrand.com' },
        { name: 'GIRL', url: 'https://www.girlskateboards.com', logoUrl: 'https://logo.clearbit.com/girlskateboards.com' },
        { name: 'REAL', url: 'https://www.realskateboards.com', logoUrl: 'https://logo.clearbit.com/realskateboards.com' },
      ],
      showInstagramFeed: false,
      instagramEmbedUrl: 'https://www.instagram.com',
      instagramHandle: '@goofyshop',
      showNumberStats: true,
      statsItems: [
        { value: '500+', label: 'Skaters' },
        { value: '24', label: 'Brands' },
        { value: '12K+', label: 'Orders' },
      ],
    },
    conversion: {
      showEmailSignup: true,
      showStickyCartSidebar: true,
      showStockWarning: true,
      showPromoCodeBanner: false,
      promoBannerText: 'Use code GOOFY20 for 20% off',
      promoBannerCode: 'GOOFY20',
      promoBannerCtaText: 'Shop Promo',
      promoBannerCtaLink: '/products',
    },
    bottom: {
      showFooter: true,
      showCookieBar: false,
      cookieBarText: 'This site uses cookies to improve your experience.',
      cookiePolicyUrl: '/privacy',
      cookieButtonText: 'Accept',
    },
  },
};

export const defaultHomePageSections: PageSection[] = [
  {
    __component: 'sections.slideshow',
    id: 0,
    slides: null,
    autoplay_seconds: 6,
    show_dots: true,
    show_overlay_text: true,
    show_buttons: true,
    show_stats: true,
    badge_text: 'GOOFY LAOS',
    heading_line_1: 'LAOS',
    heading_highlight: 'SKATE',
    heading_line_2: 'CULTURE',
    description: 'First skateboard shop & community in Laos',
    primary_cta_text: 'SHOP NOW',
    primary_cta_link: '/products',
    secondary_cta_text: 'WATCH US SKATE ▶',
    secondary_cta_link: '/about#videos',
    stats: [
      { value: '50+', label: 'Products', color: '#F8B800' },
      { value: '100+', label: 'Community', color: '#F8B800' },
      { value: '20+', label: 'Videos', color: '#F8B800' },
    ],
  },
  {
    __component: 'sections.marquee-text',
    id: 1,
    items: [
      'NEW DROP',
      'SS26 BRICK PACK',
      'FREE SHIPPING',
      'LAOS SKATE',
    ],
    background_color: '#F8B800',
    text_color: '#1A1614',
    speed: 'normal',
  },
  {
    __component: 'sections.featured-drops',
    id: 2,
    title: 'Hype Drops',
    subtitle: 'Latest drop picks',
    limit: 4,
    badge_filter: 'DROP',
    show_timer: true,
  },
  {
    __component: 'sections.category-row',
    id: 3,
    title: 'CATEGORY',
    items: [
      { title: 'Decks', subtitle: 'Street and park setups', link: '/products?type=Decks', accentColor: '#E70009' },
      { title: 'Apparel', subtitle: 'Daily wear and skate fits', link: '/products?type=Apparel', accentColor: '#FBD000' },
      { title: 'Wheels', subtitle: 'Grip, speed, and control', link: '/products?type=Wheels', accentColor: '#6B8CFF' },
      { title: 'Gear', subtitle: 'Trucks, tools, and extras', link: '/products?type=Gear', accentColor: '#00AA00' },
    ],
  },
  {
    __component: 'sections.streets-banner',
    id: 4,
    eyebrow: 'GOOFY SHOP',
    title: 'GOOFY SKATE COMMUNITY LAOS',
    subtitle: 'First skateboard community shop in Laos with high-performance gear for daily sessions.',
    cta_text: 'Shop The Drop',
    cta_link: '/products',
    background_image: null,
  },
  {
    __component: 'sections.new-arrivals',
    id: 5,
    title: 'NEW PRODUCTS',
    subtitle: '',
    limit: 6,
    badge_filter: 'NEW',
  },
  {
    __component: 'sections.new-arrivals',
    id: 6,
    title: 'PRODUCTS ON SALE',
    subtitle: '',
    limit: 6,
    badge_filter: 'SALE',
  },
  {
    __component: 'sections.new-arrivals',
    id: 7,
    title: 'POPULAR PRODUCTS',
    subtitle: '',
    limit: 6,
    badge_filter: 'HOT',
  },
  {
    __component: 'sections.new-arrivals',
    id: 8,
    title: 'COLLAB',
    subtitle: 'Limited partnerships and tight stock',
    limit: 4,
    badge_filter: 'COLLAB',
  },
  {
    __component: 'sections.testimonials',
    id: 9,
    title: 'THE VERDICT',
    items: [
      { quote: 'Best setup I have ridden all year. Fast shipping too.', author: 'Mason R.' },
      { quote: 'Quality is premium. Looks clean and feels solid on every session.', author: 'Aiko T.' },
      { quote: 'Drop day support was quick, and the deck arrived perfect.', author: 'Jordan K.' },
    ],
  },
  {
    __component: 'sections.sponsor-strip',
    id: 10,
    title: 'TRUSTED BY THE CULTURE',
    logos: [
      { name: 'BAKER', url: 'https://www.bakerskateboards.com', logoUrl: 'https://logo.clearbit.com/bakerskateboards.com' },
      { name: 'PALACE', url: 'https://www.palaceskateboards.com', logoUrl: 'https://logo.clearbit.com/palaceskateboards.com' },
      { name: 'PRIMITIVE', url: 'https://primitiveskate.com', logoUrl: 'https://logo.clearbit.com/primitiveskate.com' },
      { name: 'ENJOI', url: 'https://enjoico.com', logoUrl: 'https://logo.clearbit.com/enjoico.com' },
      { name: 'SANTA CRUZ', url: 'https://santacruzskateboards.com', logoUrl: 'https://logo.clearbit.com/santacruzskateboards.com' },
      { name: 'ELEMENT', url: 'https://www.elementbrand.com', logoUrl: 'https://logo.clearbit.com/elementbrand.com' },
      { name: 'GIRL', url: 'https://www.girlskateboards.com', logoUrl: 'https://logo.clearbit.com/girlskateboards.com' },
      { name: 'REAL', url: 'https://www.realskateboards.com', logoUrl: 'https://logo.clearbit.com/realskateboards.com' },
    ],
  },
];

const defaultYoutubeLinksSection: PageSection = {
  __component: 'sections.youtube-links',
  id: 11,
  title: 'YOUTUBE LINKS',
  subtitle: 'Latest edits, tutorials, and setup videos.',
  card_style: 'original-picture',
  items: [
    {
      title: 'Street Session Highlights',
      label: 'EDIT',
      date: '2026-03-01',
      duration: '06:42',
      color_name: 'red',
      url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    },
    {
      title: 'Kickflip Basics in 5 Minutes',
      label: 'TUTORIAL',
      date: '2026-02-21',
      duration: '05:14',
      color_name: 'yellow',
      url: 'https://www.youtube.com/watch?v=aqz-KE-bpKQ',
    },
    {
      title: 'Deck Setup: Trucks + Wheels',
      label: 'HOW TO',
      date: '2026-02-10',
      duration: '08:09',
      color_name: 'blue',
      url: 'https://www.youtube.com/watch?v=jNQXAC9IVRw',
    },
    {
      title: 'Best Flatground Tricks This Week',
      label: 'WEEKLY',
      date: '2026-01-29',
      duration: '04:33',
      color_name: 'green',
      url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
    },
  ],
} as PageSection;

export const defaultAboutPageSections: PageSection[] = [defaultYoutubeLinksSection];

export const defaultSeoTitle = 'GOOFY SHOP - Streetwear & Skate';
export const defaultSeoDescription = 'GOOFY is the first skateboard shop and skate community in Laos. Premium hardware and limited drops.';

export const defaultProductsPageConfig: ResolvedProductsPageConfig = {
  seoTitle: 'Products | GOOFY SHOP',
  seoDescription: 'Browse all products, filter by type, sort, and add to cart.',
  showMarquee: true,
  showHeroScene: true,
  pageTitle: 'OUR PRODUCTS',
  defaultCategory: 'All',
  defaultSort: 'featured',
  defaultView: 'grid',
  initialFavoritesOnly: false,
  productsLimit: 12,
  enableCategoryTabs: true,
  enableSort: true,
  enableSearch: true,
  enableViewToggle: true,
  enableWishlist: true,
  enableTopStats: true,
  promoText: 'Buy 2 get 1 free on selected drops',
  promoCtaText: 'Grab Deal ->',
};

export const defaultLocationsPageConfig: ResolvedLocationsPageConfig = {
  seoTitle: 'Locations | GOOFY SHOP',
  seoDescription: 'Explore Laos skateparks, filter by style, and open Google Maps directions.',
  menuEnabled: true,
  menuLabel: 'Location',
  pageTitle: 'Skate Parks',
  searchPlaceholder: 'skate parks',
  parks: [
    {
      id: 'vientiane-skatepark',
      name: 'Vientiane Skatepark',
      address: 'Skatepark · 2J45+F5R',
      placeCode: '2J45+F5R',
      categoryLabel: 'Skatepark',
      reviewSnippet: 'Very big and very nice',
      rating: 5,
      reviewsCount: 6,
      status: 'closed',
      opensText: 'Opens 4 PM',
      accessType: 'free',
      environmentType: 'outdoor',
      hasBowl: false,
      hasStreet: true,
      hasNight: false,
      tags: ['laos', 'street'],
      distance: '',
      photoCount: 6,
      mapsQuery: 'Vientiane Skatepark, Laos',
      imageUrl: 'https://source.unsplash.com/1200x800/?skatepark,laos,city&sig=701',
    },
    {
      id: 'caracter-skate-park',
      name: 'CARACTER SKATE PARK',
      address: 'Skatepark · XHQH+J8',
      placeCode: 'XHQH+J8',
      categoryLabel: 'Skatepark',
      reviewSnippet: 'I cannot skate but enjoy the cafe and classic cars',
      rating: 3.7,
      reviewsCount: 3,
      status: 'closed',
      opensText: 'Opens 3 PM',
      accessType: 'free',
      environmentType: 'outdoor',
      hasBowl: true,
      hasStreet: true,
      hasNight: false,
      tags: ['laos', 'park'],
      distance: '',
      photoCount: 3,
      mapsQuery: 'CARACTER SKATE PARK, Laos',
      imageUrl: 'https://source.unsplash.com/1200x800/?skatepark,concrete,asia&sig=702',
    },
    {
      id: 'skate-park-xj56',
      name: 'Skate Park',
      address: 'Skatepark · XJ56+HGQ',
      placeCode: 'XJ56+HGQ',
      categoryLabel: 'Skatepark',
      reviewSnippet: '',
      rating: 0,
      reviewsCount: 0,
      status: 'open',
      opensText: 'Open 24 hours',
      accessType: 'free',
      environmentType: 'outdoor',
      hasBowl: false,
      hasStreet: true,
      hasNight: false,
      tags: ['laos', 'street'],
      distance: '',
      photoCount: 0,
      mapsQuery: 'Skate Park XJ56+HGQ, Laos',
      imageUrl: 'https://source.unsplash.com/1200x800/?skatepark,plaza,laos&sig=703',
    },
    {
      id: 'chic-chic-skate-park',
      name: 'Chic Chic Skate Park',
      address: 'Skatepark · VG33+C67',
      placeCode: 'VG33+C67',
      categoryLabel: 'Skatepark',
      reviewSnippet: '',
      rating: 4.2,
      reviewsCount: 20,
      status: 'open',
      opensText: 'Opens 10 AM',
      accessType: 'paid',
      environmentType: 'outdoor',
      hasBowl: false,
      hasStreet: true,
      hasNight: true,
      tags: ['laos', 'night'],
      distance: '',
      photoCount: 20,
      mapsQuery: 'Chic Chic Skate Park, Laos',
      imageUrl: 'https://source.unsplash.com/1200x800/?night,amusement,asia&sig=704',
    },
  ],
};
